<?php
declare(strict_types=1);

require __DIR__ . '/_init.php';

use Saqf\Core\Audit;
use Saqf\Core\Clock;
use Saqf\Core\Config;
use Saqf\Core\Mailer;
use Saqf\Core\Policy;
use Saqf\Core\Request;
use Saqf\Core\Secrets;
use Saqf\Security\AccessReview;
use Saqf\Security\Oidc;
use Saqf\Security\SecurityCenter;
use Saqf\Security\SelfTest;
use Saqf\Web\View as V;

// A printable account of SAQF's security controls on THIS installation, for IT security and the
// university's information-security committee. Every statement is read from the running system's
// configuration and recorded results — nothing here is a fixed assurance. It is a self-assessment:
// not a penetration test, an independent audit or a certification. The closing fingerprint lets the
// printed copy be matched to the audit log.
$user = saqf_page(['admin']);
$checks = SecurityCenter::checks();
$self = SelfTest::runAndStore();
$verify = Audit::verify();
$review = AccessReview::progress();
$people = SecurityCenter::people();
$week = SecurityCenter::week();
$inPlace = count(array_filter($checks, static fn($c) => $c['ok'] === true));
$attention = array_values(array_filter($checks, static fn($c) => $c['ok'] === false));
$optional = array_values(array_filter($checks, static fn($c) => $c['ok'] === null));
$body = json_encode([$checks, $self['tests'], $verify['checked'], $review, Config::env()]);
$fingerprint = strtoupper(substr(hash('sha256', $body . Clock::stamp()), 0, 16));
Audit::record('security.report_generated', 'system', $fingerprint, "Security evidence report {$fingerprint} generated by {$user['full_name']}");

// "How this installation is set up": each sentence depends on the configuration or the records.
$sso = Oidc::enabled();
$mfaPolicy = Policy::get('auth.mfa_required');
$key = Secrets::keyStatus();
$scans = SecurityCenter::scans();
$clam = (string) Config::get('SAQF_CLAMAV_HOST', '');
$design = [
    ['Who can get in', ($sso
            ? 'University single sign-on with ' . parse_url((string) Config::get('SAQF_OIDC_ISSUER'), PHP_URL_HOST) . ' (OpenID Connect with PKCE, signed ID tokens and nonce). Two-step verification for these sign-ins is the identity provider\'s policy' . (Oidc::requireMfa() ? '; SAQF also refuses ID tokens that do not report it.' : ' and is not enforced by SAQF; university IT must confirm it.')
            : 'University single sign-on is not configured: everyone signs in with a SAQF password.')
        . ' Passwords: hashed with ' . (defined('PASSWORD_ARGON2ID') ? 'Argon2id' : 'bcrypt') . ', at least ' . Policy::get('auth.min_password_length') . ' characters, common and guessable passwords refused. Two-step verification for password sign-in is required for: ' . ['off' => 'nobody', 'admins' => 'administrators', 'all' => 'everyone'][$mfaPolicy] . '. Lockout after ' . Policy::get('auth.max_failed_logins') . ' failures and per-address throttling.'],
    ['What each person can see', 'Server-side role and scope checks on every page and action (faculty, Head of Department, Quality, dean, leadership, administrator). A denied attempt is recorded. Administrators run the system but make no academic decisions.'],
    ['How changes are controlled', 'Anti-forgery tokens on every change, re-confirmation of identity for sensitive administrator actions, a stated reason for access changes. Access review: ' . (int) $review['current'] . ' of ' . (int) $review['total'] . ' accounts confirmed within ' . (int) $review['days'] . ' days.'],
    ['What is recorded', 'Important actions go into a hash-chained audit log: tamper-evident, not tamper-proof. Verifying the chain reveals an edited or deleted entry (' . ($verify['ok'] ? 'verified intact just now, ' . (int) $verify['checked'] . ' entries' : 'BROKEN — see above') . '); it cannot stop someone with database administrator rights from changing rows. Append-only database triggers: ' . (SecurityCenter::auditGuarded() ? 'installed' : 'NOT found') . '.'],
    ['How data is protected', 'Student identifiers from every grade source are replaced by keyed one-way pseudonyms before storage; no student names are kept. Application key: ' . $key['message'] . ' Stored secrets are encrypted with AES-256-GCM. Uploaded evidence is checked by type and content and stored outside the web server; '
        . ($clam !== '' ? 'a virus scanner is configured (' . $scans['clean'] . ' of ' . $scans['total'] . ' stored files have a recorded clean scan).' : 'NO virus scanner is configured, so files are not scanned for malware (' . $scans['total'] . ' stored).')
        . ' Backups: ' . SecurityCenter::backupLine()],
    ['How the web layer is hardened', (Request::isHttps() ? 'This report was served over HTTPS (HSTS sent).' : 'This report was NOT served over HTTPS.') . ' Strict Content-Security-Policy with no inline scripts, frame blocking, SameSite=Strict HttpOnly cookies, idle (' . Policy::get('session.idle_minutes') . ' min) and absolute (' . Policy::get('session.absolute_hours') . ' h) session limits, sessions listed and revocable by their owner.'],
    ['How problems reach IT', 'Failing connectors, a stalled scheduler, missing or incomplete backups, a broken audit chain, a failed self-test, overdue access review, undeliverable mail, blocked malware and password guessing raise alerts in SAQF'
        . (Mailer::enabled() ? ', by e-mail' : ' (e-mail not configured)') . (Config::get('SAQF_ALERT_WEBHOOK') ? ' and to the configured webhook.' : ' (no webhook configured).')],
];
$notCovered = [
    'No penetration test, vulnerability scan or independent security review is represented here; the self-test only exercises SAQF\'s own protections.',
    'The identity provider\'s MFA and account policies, the network, firewall, operating system, database server and hosting are outside what SAQF can observe.',
    'A restore from backup is not tested by SAQF; it must be rehearsed (docs/OPERATIONS.md) and recorded by IT.',
    'This report is not a compliance certification and does not mean any NCAAA report has been approved.',
];
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Security evidence report · SAQF</title><link rel="icon" href="assets/favicon.png"><link rel="stylesheet" href="assets/app.css?v=<?= SAQF_VERSION ?>"></head>
<body class="tour"><main class="tour-main">
<header class="tour-head"><img src="assets/yu-logo.png" alt="Al Yamamah University"><div><h1>Security evidence report</h1><p class="muted">SAQF <?= V::h(SAQF_VERSION) ?> · <?= V::h(Config::env()) ?> mode · generated <?= V::h(date('j M Y H:i')) ?> by <?= V::h($user['full_name']) ?></p><p class="small"><strong>Self-assessment</strong> generated by SAQF from this installation's configuration and recorded results. It is not a penetration test, an independent audit or a certification.</p></div><div class="right row noprint"><button class="btn btn-sm btn-primary" data-print>Print / save as PDF</button><a class="btn btn-sm" href="admin.php?tab=center">Back</a></div></header>

<section class="card"><div class="card-h"><h2>Summary</h2></div><div class="card-b small">
  <div class="row between"><span>Security controls in place</span><strong><?= $inPlace ?> of <?= count($checks) ?></strong></div>
  <div class="row between"><span>Controls that need attention</span><strong><?= count($attention) ?></strong></div>
  <div class="row between"><span>Optional, not configured or not applicable here</span><strong><?= count($optional) ?></strong></div>
  <div class="row between"><span>Self-test checks passed just now</span><strong><?= (int) $self['passed'] ?> of <?= (int) $self['total'] ?></strong></div>
  <div class="row between"><span>Audit log</span><strong><?= $verify['ok'] ? 'Hash chain intact · ' . (int) $verify['checked'] . ' entries verified' : 'BROKEN' ?></strong></div>
  <div class="row between"><span>Access review</span><strong><?= (int) $review['current'] ?> of <?= (int) $review['total'] ?> accounts confirmed in <?= (int) $review['days'] ?> days</strong></div>
  <div class="row between"><span>Administrators with two-step verification</span><strong><?= (int) $people['admins_mfa'] ?> of <?= (int) $people['admins_local'] ?> password-using</strong></div>
</div></section>

<?php if ($attention): ?>
<section class="card"><div class="card-h"><h2>Needs attention</h2></div><div class="card-b tight"><table><tbody>
<?php foreach ($attention as $c): ?><tr><td style="width:34px"><?= V::pill('!', 'amber') ?></td><td><strong><?= V::h($c['label']) ?></strong><div class="small"><?= V::h($c['status']) ?></div><?php if ($c['fix']): ?><div class="tiny muted">How to fix: <?= V::h($c['fix']) ?></div><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>
<?php endif; ?>

<section class="card"><div class="card-h"><h2>Controls and their live status</h2><span class="right tiny muted">✓ in place · ! needs attention · i optional, not configured or not applicable</span></div><div class="card-b tight"><table><tbody>
<?php foreach ($checks as $c): ?><tr><td style="width:34px"><?= $c['ok'] === true ? V::pill('✓', 'green') : ($c['ok'] === false ? V::pill('!', 'amber') : V::pill('i', 'grey')) ?></td><td><strong><?= V::h($c['label']) ?></strong><div class="small"><?= V::h($c['status']) ?></div></td></tr><?php endforeach; ?>
</tbody></table></div></section>

<section class="card"><div class="card-h"><h2>Self-test: SAQF exercising its own protections</h2></div><div class="card-b tight"><p class="small" style="padding:10px 14px;margin:0"><?= V::h(SelfTest::DISCLAIMER) ?></p><table><tbody>
<?php foreach ($self['tests'] as $t): ?><tr><td style="width:34px"><?= $t['ok'] ? V::pill('✓', 'green') : V::pill('!', 'red') ?></td><td><strong><?= V::h($t['name']) ?></strong> <span class="muted small">· <?= V::h($t['what']) ?></span><div class="small"><?= V::h($t['detail']) ?></div></td></tr><?php endforeach; ?>
</tbody></table></div></section>

<section class="card"><div class="card-h"><h2>How this installation is set up</h2><span class="right tiny muted">read from its configuration and records just now</span></div><div class="card-b tight"><table><tbody>
<?php foreach ($design as [$q, $a]): ?><tr><td style="width:190px"><strong><?= V::h($q) ?></strong></td><td class="small"><?= V::h($a) ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>

<section class="card"><div class="card-h"><h2>Not covered by this report</h2></div><div class="card-b small"><ul style="margin:0;padding-inline-start:18px">
<?php foreach ($notCovered as $n): ?><li><?= V::h($n) ?></li><?php endforeach; ?></ul></div></section>

<section class="card"><div class="card-h"><h2>Last 7 days</h2></div><div class="card-b small">
<?php foreach ($week as $label => $n): ?><div class="row between"><span><?= V::h($label) ?></span><strong><?= (int) $n ?></strong></div><?php endforeach; ?></div></section>

<p class="small muted">Report fingerprint <strong class="mono"><?= V::h($fingerprint) ?></strong>: generating this report is itself entered in the audit log under this code, so a printed copy can be matched to the system. This is a statement of how the system is configured and behaving, not a compliance certification.</p>
</main><script src="assets/app.js?v=<?= SAQF_VERSION ?>" defer></script></body></html>
