<?php
declare(strict_types=1);

require __DIR__ . '/_init.php';

use Saqf\Core\Audit;
use Saqf\Core\Clock;
use Saqf\Core\Config;
use Saqf\Core\Policy;
use Saqf\Security\AccessReview;
use Saqf\Security\SecurityCenter;
use Saqf\Security\SelfTest;
use Saqf\Web\View as V;

// A printable, self-contained account of SAQF's security controls on THIS installation, for
// auditors, IT security and the university's information-security committee. Every line is read
// from the running system; the closing fingerprint lets the printed copy be matched to the log.
$user = saqf_page(['admin']);
$checks = SecurityCenter::checks();
$self = SelfTest::runAndStore();
$verify = Audit::verify();
$review = AccessReview::progress();
$people = SecurityCenter::people();
$week = SecurityCenter::week();
$inPlace = count(array_filter($checks, static fn($c) => $c['ok'] === true));
$attention = array_filter($checks, static fn($c) => $c['ok'] === false);
$body = json_encode([$checks, $self['tests'], $verify['checked'], $review, Config::env()]);
$fingerprint = strtoupper(substr(hash('sha256', $body . Clock::stamp()), 0, 16));
Audit::record('security.report_generated', 'system', $fingerprint, "Security evidence report {$fingerprint} generated by {$user['full_name']}");
$design = [
    ['Who can get in', 'University single sign-on (OpenID Connect with PKCE, signed ID tokens and nonce). Local passwords hashed with Argon2id; common words, keyboard runs, names and the university name refused. Two-step verification (standard authenticator apps, single-use recovery codes). Lockout after repeated failures and per-address throttling.'],
    ['What each person can see', 'Server-side role and scope checks on every page and action (faculty, Head of Department, Quality, dean, leadership, administrator). A denied attempt is recorded. Administrators run the system but make no academic decisions.'],
    ['How changes are controlled', 'Anti-forgery tokens on every change, re-confirmation of identity for sensitive administrator actions, a stated reason for access changes, and an access review where another administrator confirms every person\'s role on a schedule.'],
    ['What is recorded', 'Every important action goes into a hash-chained, append-only audit log. The chain is re-verified every night and on demand; any edit or deletion is detected and raises an IT alert.'],
    ['How data is protected', 'Student identifiers from the LMS are replaced by keyed one-way pseudonyms before storage, and no student names are kept. Secrets are encrypted with AES-256-GCM. Uploaded evidence is virus-scanned and stored outside the web server. Backups are encrypted and copied off-site.'],
    ['How the web layer is hardened', 'HTTPS with HSTS, strict Content-Security-Policy with no inline scripts, frame blocking, SameSite=Strict HttpOnly cookies, idle and absolute session limits, sessions listed and revocable by their owner.'],
    ['How problems reach IT', 'Failing connectors, a stalled scheduler, missing backups, a broken audit chain, failed self-test, overdue access review, undeliverable mail, blocked malware and password guessing raise alerts by themselves (in SAQF, by e-mail and to a Teams/Slack webhook).'],
];
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Security evidence report · SAQF</title><link rel="icon" href="assets/favicon.png"><link rel="stylesheet" href="assets/app.css?v=<?= SAQF_VERSION ?>"></head>
<body class="tour"><main class="tour-main">
<header class="tour-head"><img src="assets/yu-logo.png" alt="Al Yamamah University"><div><h1>Security evidence report</h1><p class="muted">SAQF <?= V::h(SAQF_VERSION) ?> · <?= V::h(Config::env()) ?> mode · generated <?= V::h(date('j M Y H:i')) ?> by <?= V::h($user['full_name']) ?></p></div><div class="right row noprint"><button class="btn btn-sm btn-primary" data-print>Print / save as PDF</button><a class="btn btn-sm" href="admin.php?tab=center">Back</a></div></header>

<section class="card"><div class="card-h"><h2>Summary</h2></div><div class="card-b small">
  <div class="row between"><span>Security controls in place</span><strong><?= $inPlace ?> of <?= count($checks) ?></strong></div>
  <div class="row between"><span>Controls that need attention</span><strong><?= count($attention) ?></strong></div>
  <div class="row between"><span>Protections proved by live self-test just now</span><strong><?= (int) $self['passed'] ?> of <?= (int) $self['total'] ?></strong></div>
  <div class="row between"><span>Audit log</span><strong><?= $verify['ok'] ? 'Intact · ' . (int) $verify['checked'] . ' entries verified' : 'BROKEN' ?></strong></div>
  <div class="row between"><span>Access review</span><strong><?= (int) $review['current'] ?> of <?= (int) $review['total'] ?> accounts confirmed in <?= (int) $review['days'] ?> days</strong></div>
  <div class="row between"><span>Administrators with two-step verification</span><strong><?= (int) $people['admins_mfa'] ?> of <?= (int) $people['admins_local'] ?> password-using</strong></div>
</div></section>

<section class="card"><div class="card-h"><h2>Controls and their live status</h2></div><div class="card-b tight"><table><tbody>
<?php foreach ($checks as $c): ?><tr><td style="width:34px"><?= $c['ok'] === true ? V::pill('✓', 'green') : ($c['ok'] === false ? V::pill('!', 'amber') : V::pill('i', 'grey')) ?></td><td><strong><?= V::h($c['label']) ?></strong><div class="small"><?= V::h($c['status']) ?></div></td></tr><?php endforeach; ?>
</tbody></table></div></section>

<section class="card"><div class="card-h"><h2>Live self-test: each protection tried for real</h2></div><div class="card-b tight"><table><tbody>
<?php foreach ($self['tests'] as $t): ?><tr><td style="width:34px"><?= $t['ok'] ? V::pill('✓', 'green') : V::pill('!', 'red') ?></td><td><strong><?= V::h($t['name']) ?></strong> <span class="muted small">· <?= V::h($t['what']) ?></span><div class="small"><?= V::h($t['detail']) ?></div></td></tr><?php endforeach; ?>
</tbody></table></div></section>

<section class="card"><div class="card-h"><h2>How the system is designed to stay secure</h2></div><div class="card-b tight"><table><tbody>
<?php foreach ($design as [$q, $a]): ?><tr><td style="width:190px"><strong><?= V::h($q) ?></strong></td><td class="small"><?= V::h($a) ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>

<section class="card"><div class="card-h"><h2>Last 7 days</h2></div><div class="card-b small">
<?php foreach ($week as $label => $n): ?><div class="row between"><span><?= V::h($label) ?></span><strong><?= (int) $n ?></strong></div><?php endforeach; ?></div></section>

<p class="small muted">Report fingerprint <strong class="mono"><?= V::h($fingerprint) ?></strong>: generating this report is itself entered in the audit log under this code, so a printed copy can be matched to the system. This is a statement of how the system is configured and behaving, not a compliance certification.</p>
</main><script src="assets/app.js?v=<?= SAQF_VERSION ?>" defer></script></body></html>
