<?php
declare(strict_types=1);

namespace Saqf\Demo;

/**
 * The demonstration scenario. All people are FICTIONAL demo accounts; programs,
 * courses, prerequisites and PLOs come from the YU public study-plan snapshot.
 * Student results are synthetic and pseudonymous, generated by bin/build_demo_data.php.
 *
 * A small cast so every feature can be shown in a few minutes — one account per role, plus the
 * second instructor who teaches a section and the business-school instructor:
 *  - Dr. Omar (faculty) coordinates SWE 401: CLO3 misses its target two terms running; the first
 *    improvement action is followed by a measurable improvement, but the gap recurs → recurring gap
 *    for the HoD. SWE 401 runs in two sections (Dr. Sara teaches section 02) and the sections differ.
 *  - Dr. Omar's SWE 412 revision has four deterministic errors (the live demo fixes them), and his
 *    CIS 491 capstone carries a weighting above policy → a justified exception request for QA.
 *  - Dr. Sara's SWE 302 midterm grades are "about to be published" by the LMS → early warning.
 *  - SWE SO2 stays below target across terms → the Dean sees a persistent PLO issue.
 *  - Business: ACC 311 (healthy, shared with Finance) and MIS 327 (one gap with an action); their
 *    existing specifications arrive through the bulk specification import.
 *  - The SIS later assigns SWE 413 to a newly hired instructor SAQF does not know yet: the account
 *    and the workspace are created automatically.
 *  - Data: the published MIS plan lists MIS 316 with two different credit values.
 */
final class Story
{
    public const PASSWORD = 'Yamamah@2026';
    /** The demo scenario's "today": Fall 2026, week 6. The installer anchors the demo clock here. */
    public const DEMO_NOW = '2026-10-01 09:00:00';

    public const USERS = [
        // username, full name, title, role, department code, college code, external id
        ['f.omar', 'Dr. Omar Al-Harbi', 'Assistant Professor', 'faculty', 'CED', null, 'YU-F1034'],
        ['hod.ced', 'Dr. Abdullah Al-Otaibi', 'Head, Computer Engineering Department', 'hod', 'CED', null, 'YU-H0101'],
        ['qa.director', 'Dr. Huda Al-Rashid', 'Director, Quality & Academic Accreditation', 'qa', null, null, 'YU-Q0001'],
        ['dean.coe', 'Dr. Mansour Al-Shammari', 'Dean, College of Engineering', 'dean', null, 'COE', 'YU-D0001'],
        ['vp.academic', 'Dr. Fahad Al-Sudairi', 'Vice President for Academic Affairs', 'leadership', null, null, 'YU-L0001'],
        ['it.admin', 'Saleh Al-Anazi', 'IT Systems Administrator', 'admin', null, null, 'YU-IT001'],
        ['f.sara', 'Dr. Sara Al-Qahtani', 'Associate Professor', 'faculty', 'CED', null, 'YU-F1021'],
        ['f.noura', 'Dr. Noura Al-Shehri', 'Assistant Professor', 'faculty', 'AFD', null, 'YU-F2011'],
    ];

    /** The six accounts shown as one-click role buttons in demo mode (one per role). */
    public const ROLE_ACCOUNTS = ['f.omar', 'hod.ced', 'qa.director', 'dean.coe', 'vp.academic', 'it.admin'];

    /** The administrator's two-step verification secret in demo mode only (base32). */
    public const ADMIN_TOTP_SECRET = 'JBSWY3DPEHPK3PXPSAQFDEMO';

    public const TERMS = [
        ['code' => '2025-1', 'name' => 'Fall 2025', 'academic_year' => '2025-2026', 'sequence' => 1, 'starts_on' => '2025-08-24', 'ends_on' => '2025-12-18', 'grades_due_on' => '2025-12-28'],
        ['code' => '2025-2', 'name' => 'Spring 2026', 'academic_year' => '2025-2026', 'sequence' => 2, 'starts_on' => '2026-01-11', 'ends_on' => '2026-05-14', 'grades_due_on' => '2026-05-24'],
        ['code' => '2026-1', 'name' => 'Fall 2026', 'academic_year' => '2026-2027', 'sequence' => 3, 'starts_on' => '2026-08-23', 'ends_on' => '2026-12-17', 'grades_due_on' => '2026-12-27'],
        ['code' => '2026-2', 'name' => 'Spring 2027', 'academic_year' => '2026-2027', 'sequence' => 4, 'starts_on' => '2027-01-10', 'ends_on' => '2027-05-13', 'grades_due_on' => '2027-05-23'],
    ];

    /**
     * Specifications. clos: [statement, domain, [program => [PLO codes]]].
     * assessments: [name, kind, weight, week, [CLO indexes (1-based)]].
     */
    public const SPECS = [
        'CIS 443' => [
            'author' => 'f.sara',
            'objectives' => 'Enable students to design, deploy and evaluate secure, cost-aware applications on public cloud platforms.',
            'strategies' => 'Interactive lectures, guided cloud labs, a team deployment project and case-based discussions.',
            'clos' => [
                ['Explain cloud service and deployment models and their trade-offs.', 'Knowledge and Understanding', ['SWE' => ['SO1']]],
                ['Design and deploy a scalable application on a cloud platform.', 'Skills', ['SWE' => ['SO2']]],
                ['Evaluate the security and cost implications of a cloud architecture.', 'Skills', ['SWE' => ['SO1', 'SO4']]],
                ['Collaborate in a team to present a cloud migration proposal.', 'Values, Autonomy, and Responsibility', ['SWE' => ['SO3', 'SO5']]],
            ],
            'assessments' => [
                ['Quiz 1', 'quiz', 10, 4, [1]],
                ['Midterm exam', 'midterm', 25, 7, [1, 3]],
                ['Cloud deployment project', 'project', 30, 13, [2, 4]],
                ['Team presentation', 'presentation', 10, 14, [4]],
                ['Final exam', 'final', 25, 16, [1, 2, 3]],
            ],
            'topics' => [['Cloud computing concepts and service models', 6], ['Virtualisation and containers', 9], ['Cloud storage and networking', 9], ['Deploying and scaling applications', 12], ['Cloud security, cost and governance', 9]],
            'resources' => [['essential', 'Erl, T. et al. Cloud Computing: Concepts, Technology & Architecture (2nd ed.)'], ['electronic', 'Cloud provider academic labs (sandbox accounts)'], ['facility', 'Computer lab with internet access and cloud CLI tools']],
        ],
        'SWE 401' => [
            'author' => 'f.omar',
            'objectives' => 'Develop the ability to plan, perform and justify software quality assurance activities across the development life cycle.',
            'strategies' => 'Lectures, inspection workshops, a team QA-plan project and reflective writing.',
            'clos' => [
                ['Describe software quality models and standards such as ISO/IEC 25010 and CMMI.', 'Knowledge and Understanding', ['SWE' => ['SO1']]],
                ['Apply review and inspection techniques to software artifacts.', 'Skills', ['SWE' => ['SO1', 'SO2']]],
                ['Design a test and quality assurance plan for a software project.', 'Skills', ['SWE' => ['SO2']]],
                ['Justify quality decisions in a written report to project stakeholders.', 'Values, Autonomy, and Responsibility', ['SWE' => ['SO3', 'SO4']]],
            ],
            'assessments' => [
                ['Quiz', 'quiz', 10, 4, [1]],
                ['Midterm exam', 'midterm', 30, 8, [1, 2]],
                ['QA plan project', 'project', 30, 13, [3, 4]],
                ['Final exam', 'final', 30, 16, [2, 3]],
            ],
            'topics' => [['Software quality concepts and models', 6], ['Standards: ISO/IEC 25010, ISO 9001, CMMI', 6], ['Reviews, walkthroughs and inspections', 9], ['Test planning and test design', 12], ['Quality metrics and reporting', 9]],
            'resources' => [['essential', 'Galin, D. Software Quality: Concepts and Practice'], ['supportive', 'ISO/IEC 25010 product quality model (summary notes)'], ['facility', 'Software lab with test-management tools']],
        ],
        'SWE 302' => [
            'author' => 'f.sara',
            'objectives' => 'Prepare students to design and evaluate software architectures that satisfy functional and quality requirements.',
            'strategies' => 'Lectures, architecture katas, design studio sessions and peer design reviews.',
            'clos' => [
                ['Explain architectural styles and patterns such as layered, client-server and MVC.', 'Knowledge and Understanding', ['SWE' => ['SO1']]],
                ['Design a software architecture that satisfies functional and quality requirements.', 'Skills', ['SWE' => ['SO2']]],
                ['Evaluate alternative designs using quality-attribute trade-off analysis.', 'Skills', ['SWE' => ['SO1', 'SO2']]],
                ['Communicate design decisions through architecture documentation and presentation.', 'Values, Autonomy, and Responsibility', ['SWE' => ['SO3', 'SO5']]],
            ],
            'assessments' => [
                ['Quiz', 'quiz', 10, 3, [1]],
                ['Midterm exam', 'midterm', 25, 7, [1, 3]],
                ['Design project', 'project', 35, 12, [2, 4]],
                ['Final exam', 'final', 30, 16, [2, 3]],
            ],
            'topics' => [['Architecture concepts and views', 6], ['Architectural styles and patterns', 12], ['Quality attributes and tactics', 9], ['Design evaluation (ATAM-style trade-offs)', 9], ['Documenting architecture', 6]],
            'resources' => [['essential', 'Bass, Clements & Kazman. Software Architecture in Practice (4th ed.)'], ['electronic', 'C4 model and UML modelling tool licences'], ['facility', 'Design studio room with projection']],
        ],
        'SWE 412' => [
            'author' => 'f.omar',
            'objectives' => 'Enable students to design, build and evaluate usable mobile applications.',
            'strategies' => 'Hands-on labs, iterative app project, usability testing sessions.',
            'clos' => [
                ['Describe mobile platform architectures and application life cycles.', 'Knowledge and Understanding', ['SWE' => ['SO1']]],
                ['Develop a mobile application that uses local storage and network services.', 'Skills', ['SWE' => ['SO2']]],
                ['Evaluate the usability of a mobile interface with representative users.', 'Skills', ['SWE' => ['SO2', 'SO3']]],
            ],
            'assessments' => [
                ['Lab assignments', 'lab', 20, 10, [2]],
                ['Midterm exam', 'midterm', 25, 7, [1]],
                ['Mobile app project', 'project', 35, 14, [2, 3]],
                ['Final exam', 'final', 20, 16, [1, 3]],
            ],
            'topics' => [['Mobile platforms and app life cycle', 6], ['UI patterns and navigation', 9], ['Local storage and networking', 12], ['Usability evaluation', 6], ['Testing and publishing', 6]],
            'resources' => [['essential', 'Platform developer documentation (Android / iOS)'], ['facility', 'Mobile development lab with test devices']],
        ],
        'CIS 491' => [
            'author' => 'f.omar',
            'objectives' => 'Guide student teams to formulate and design a capstone software project.',
            'strategies' => 'Supervised team work, milestone reviews, proposal defence.',
            'clos' => [
                ['Formulate a software project proposal with measurable requirements.', 'Skills', ['SWE' => ['SO1'], 'CNE' => ['SO1']]],
                ['Design a solution architecture for the proposed system.', 'Skills', ['SWE' => ['SO2'], 'CNE' => ['SO2']]],
                ['Present the project plan to a technical audience.', 'Values, Autonomy, and Responsibility', ['SWE' => ['SO3'], 'CNE' => ['SO3']]],
                ['Plan team responsibilities and professional conduct for the project.', 'Values, Autonomy, and Responsibility', ['SWE' => ['SO4', 'SO5'], 'CNE' => ['SO4', 'SO5']]],
            ],
            'assessments' => [
                ['Proposal and design report', 'report', 70, 14, [1, 2, 4]],
                ['Progress presentation', 'presentation', 30, 15, [3, 4]],
            ],
            'topics' => [['Project selection and scoping', 6], ['Requirements and proposal writing', 12], ['Solution design', 15], ['Project planning and teamwork', 9]],
            'resources' => [['essential', 'YU graduation project handbook'], ['facility', 'Project lab and supervisor meeting rooms']],
        ],
        'CNE 307' => [
            'author' => 'f.sara',
            'objectives' => 'Develop the knowledge and practical skills to secure enterprise networks.',
            'strategies' => 'Lectures, hands-on security labs and incident-analysis case studies.',
            'clos' => [
                ['Explain network security threats, vulnerabilities and attack techniques.', 'Knowledge and Understanding', ['CNE' => ['SO1']]],
                ['Configure firewalls, VPNs and intrusion detection to secure a network.', 'Skills', ['CNE' => ['SO2', 'SO6']]],
                ['Analyze security incidents using packet captures and logs.', 'Skills', ['CNE' => ['SO6']]],
                ['Recognize ethical and legal responsibilities in network security practice.', 'Values, Autonomy, and Responsibility', ['CNE' => ['SO4']]],
            ],
            'assessments' => [
                ['Quiz', 'quiz', 10, 4, [1]],
                ['Lab work', 'lab', 25, 12, [2, 3]],
                ['Midterm exam', 'midterm', 25, 8, [1, 4]],
                ['Final exam', 'final', 40, 16, [2, 3, 4]],
            ],
            'topics' => [['Threats and attack techniques', 9], ['Firewalls and VPNs', 12], ['Intrusion detection and monitoring', 12], ['Incident analysis', 6], ['Ethics and cyber law', 3]],
            'resources' => [['essential', 'Stallings, W. Network Security Essentials'], ['facility', 'Networking lab with virtualised security appliances']],
        ],
        'ACC 311' => [
            'author' => 'f.noura',
            'objectives' => 'Build competence in recognising, measuring and reporting financial information under IFRS as endorsed in Saudi Arabia.',
            'strategies' => 'Lectures, worked problems, case analysis.',
            'clos' => [
                ['Explain the conceptual framework and IFRS recognition and measurement principles.', 'Knowledge and Understanding', ['ACC' => ['PLO1', 'PLO2'], 'FIN' => ['PLO1']]],
                ['Prepare financial statements in accordance with IFRS as endorsed in Saudi Arabia.', 'Skills', ['ACC' => ['PLO3'], 'FIN' => ['PLO3']]],
                ['Analyze accounting transactions for revenue, receivables and inventory.', 'Skills', ['ACC' => ['PLO4', 'PLO5'], 'FIN' => ['PLO5']]],
                ['Demonstrate ethical judgement in accounting policy choices.', 'Values, Autonomy, and Responsibility', ['ACC' => ['PLO8'], 'FIN' => ['PLO8']]],
            ],
            'assessments' => [
                ['Quiz', 'quiz', 10, 4, [1]],
                ['Midterm exam', 'midterm', 30, 8, [1, 3]],
                ['Case study', 'assignment', 20, 12, [3, 4]],
                ['Final exam', 'final', 40, 16, [2, 3]],
            ],
            'topics' => [['Conceptual framework', 6], ['Revenue recognition (IFRS 15)', 9], ['Receivables and inventory', 12], ['Financial statement preparation', 12]],
            'resources' => [['essential', 'Kieso, Weygandt & Warfield. Intermediate Accounting (IFRS edition)'], ['electronic', 'SOCPA-endorsed IFRS standards']],
        ],
        'MIS 327' => [
            'author' => 'f.noura',
            'objectives' => 'Enable students to design and query relational databases that support business processes.',
            'strategies' => 'Lectures, SQL labs, team database project with a business client brief.',
            'clos' => [
                ['Describe relational database concepts and the relational model.', 'Knowledge and Understanding', ['MIS' => ['SO1']]],
                ['Design a normalized database schema from business requirements.', 'Skills', ['MIS' => ['SO2']]],
                ['Write SQL queries to retrieve and manipulate business data.', 'Skills', ['MIS' => ['SO2', 'SO6']]],
                ['Work in a team to deliver a database project for a business client.', 'Values, Autonomy, and Responsibility', ['MIS' => ['SO5']]],
            ],
            'assessments' => [
                ['Quiz', 'quiz', 10, 4, [1]],
                ['SQL labs', 'lab', 20, 10, [3]],
                ['Midterm exam', 'midterm', 25, 8, [1, 2]],
                ['Database project', 'project', 25, 14, [2, 4]],
                ['Final exam', 'final', 20, 16, [3]],
            ],
            'topics' => [['Relational model', 6], ['ER modelling and normalisation', 12], ['SQL', 15], ['Database projects', 9]],
            'resources' => [['essential', 'Coronel & Morris. Database Systems: Design, Implementation, & Management'], ['facility', 'Lab with a relational DBMS']],
        ],
    ];

    /**
     * Offerings per term: course => [instructor, enrolled, [target CLO achievement % in CLO order], batches, sections]
     * batches: [label, published_at, [assessment names]]; future dates = not yet published by the LMS.
     * sections (multi-section courses): [[code, instructor, enrolled], …]; the first is the coordinator.
     */
    public const OFFERINGS = [
        '2025-1' => [
            'CIS 443' => ['f.sara', 30, [80, 70, 73.3, 86.7]],
            'SWE 401' => ['f.omar', 30, [76.7, 70, 53.3, 80]],
            'SWE 302' => ['f.sara', 28, [78.6, 71.4, 71.4, 85.7]],
            'CIS 491' => ['f.omar', 24, [70.8, 70.8, 83.3, 79.2]],
            'CNE 307' => ['f.sara', 26, [76.9, 73.1, 73.1, 84.6]],
            'ACC 311' => ['f.noura', 32, [78.1, 75, 71.9, 87.5]],
            'MIS 327' => ['f.noura', 25, [80, 72, 72, 84]],
        ],
        '2025-2' => [
            'CIS 443' => ['f.sara', 32, [81.3, 71.9, 75, 87.5]],
            'SWE 401' => ['f.omar', 30, [80, 70, 63.3, 83.3]],
            'SWE 302' => ['f.sara', 30, [76.7, 63.3, 70, 83.3]],
            'SWE 412' => ['f.omar', 25, [84, 72, 72]],
            'CNE 307' => ['f.sara', 27, [77.8, 74.1, 74.1, 85.2]],
            'ACC 311' => ['f.noura', 30, [80, 76.7, 73.3, 86.7]],
            'MIS 327' => ['f.noura', 26, [80.8, 73.1, 61.5, 84.6]],
        ],
        '2026-1' => [
            'CIS 443' => ['f.sara', 31, [77.4, null, 74.2, null], [['Quiz 1 and midterm grades', '2026-09-28 10:00:00', ['Quiz 1', 'Midterm exam']]]],
            'SWE 401' => ['f.omar', 29, [72.4, 72.4, null, null], [['Quiz and midterm grades', '2026-09-29 11:00:00', ['Quiz', 'Midterm exam']]], [['01', 'f.omar', 15], ['02', 'f.sara', 14]]],
            'SWE 302' => ['f.sara', 30, [76.7, null, 60, null], [['Quiz grades', '2026-09-15 09:00:00', ['Quiz']], ['Midterm exam grades', '2026-10-20 09:00:00', ['Midterm exam']]]],
            'SWE 412' => ['f.omar', 27, [null, null, null]],
            'CIS 491' => ['f.omar', 22, [null, null, null, null]],
            'SWE 411' => ['f.sara', 28, []],
            'CNE 307' => ['f.sara', 25, [76, null, null, null], [['Quiz grades', '2026-09-22 09:00:00', ['Quiz']]]],
            'ACC 311' => ['f.noura', 33, [78.8, null, 72.7, null], [['Quiz and midterm grades', '2026-09-30 12:00:00', ['Quiz', 'Midterm exam']]]],
            'MIS 327' => ['f.noura', 24, [79.2, null, null, null], [['Quiz grades', '2026-09-21 09:00:00', ['Quiz']]]],
        ],
        '2026-2' => [
            'CIS 443' => ['f.sara', 30, []],
            'SWE 401' => ['f.omar', 30, [], null, [['01', 'f.omar', 15], ['02', 'f.sara', 15]]],
            'SWE 302' => ['f.sara', 28, []],
            'SWE 412' => ['f.omar', 26, []],
            'CIS 492' => ['f.omar', 22, []],
            'CNE 307' => ['f.sara', 26, []],
            'ACC 311' => ['f.noura', 31, []],
            'MIS 327' => ['f.noura', 25, []],
        ],
    ];

    /** Courses whose existing specifications reach SAQF through the bulk import (demo of SpecImport). */
    public const IMPORTED_SPECS = ['ACC 311', 'MIS 327'];

    /** Assignments the SIS "publishes later" — released from the admin integration simulator. */
    public const PENDING_ASSIGNMENTS = [
        ['term' => '2026-1', 'course' => 'SWE 413', 'instructor' => 'YU-F1047', 'instructor_name' => 'Dr. Faisal Al-Dosari', 'instructor_email' => 'f.aldosari@demo.saqf.invalid', 'sections' => 1, 'enrolled' => 18, 'label' => 'SIS assigns SWE 413 Design Patterns to Dr. Faisal Al-Dosari, a newly hired instructor SAQF does not know yet'],
    ];

    /**
     * Arabic wording of the demo's people and course content, stored like a university would enter
     * it (Saqf\Core\Translations) so the Arabic interface and Arabic Word documents are fully Arabic.
     * Book references stay in their original language, as they would in a real course file.
     */
    public const ARABIC = [
        'people' => [
            'Dr. Omar Al-Harbi' => 'د. عمر الحربي',
            'Dr. Abdullah Al-Otaibi' => 'د. عبدالله العتيبي',
            'Dr. Huda Al-Rashid' => 'د. هدى الراشد',
            'Dr. Mansour Al-Shammari' => 'د. منصور الشمري',
            'Dr. Fahad Al-Sudairi' => 'د. فهد السديري',
            'Saleh Al-Anazi' => 'صالح العنزي',
            'Dr. Sara Al-Qahtani' => 'د. سارة القحطاني',
            'Dr. Noura Al-Shehri' => 'د. نورة الشهري',
            'Dr. Faisal Al-Dosari' => 'د. فيصل الدوسري',
            'Assistant Professor' => 'أستاذ مساعد',
            'Associate Professor' => 'أستاذ مشارك',
            'Professor' => 'أستاذ',
            'Head, Computer Engineering Department' => 'رئيس قسم هندسة الحاسب',
            'Director, Quality & Academic Accreditation' => 'مدير الجودة والاعتماد الأكاديمي',
            'Dean, College of Engineering' => 'عميد كلية الهندسة',
            'Vice President for Academic Affairs' => 'وكيل الجامعة للشؤون الأكاديمية',
            'IT Systems Administrator' => 'مسؤول أنظمة تقنية المعلومات',
        ],
        'content' => [
            // CIS 443
            'Enable students to design, deploy and evaluate secure, cost-aware applications on public cloud platforms.' => 'تمكين الطلاب من تصميم تطبيقات آمنة ومراعية للتكلفة على المنصات السحابية العامة ونشرها وتقييمها.',
            'Interactive lectures, guided cloud labs, a team deployment project and case-based discussions.' => 'محاضرات تفاعلية، ومعامل سحابية موجّهة، ومشروع نشر جماعي، ونقاشات قائمة على دراسات الحالة.',
            'Explain cloud service and deployment models and their trade-offs.' => 'شرح نماذج الخدمة والنشر السحابية والموازنة بينها.',
            'Design and deploy a scalable application on a cloud platform.' => 'تصميم تطبيق قابل للتوسع ونشره على منصة سحابية.',
            'Evaluate the security and cost implications of a cloud architecture.' => 'تقييم الآثار الأمنية والمالية لمعمارية سحابية.',
            'Collaborate in a team to present a cloud migration proposal.' => 'التعاون ضمن فريق لعرض مقترح للانتقال إلى السحابة.',
            'Quiz 1' => 'الاختبار القصير 1',
            'Cloud deployment project' => 'مشروع النشر السحابي',
            'Team presentation' => 'العرض الجماعي',
            'Cloud computing concepts and service models' => 'مفاهيم الحوسبة السحابية ونماذج الخدمة',
            'Virtualisation and containers' => 'المحاكاة الافتراضية والحاويات',
            'Cloud storage and networking' => 'التخزين والشبكات السحابية',
            'Deploying and scaling applications' => 'نشر التطبيقات وتوسيعها',
            'Cloud security, cost and governance' => 'أمن السحابة وتكلفتها وحوكمتها',
            'Cloud provider academic labs (sandbox accounts)' => 'المعامل الأكاديمية لمزودي الخدمات السحابية (حسابات تجريبية)',
            'Computer lab with internet access and cloud CLI tools' => 'معمل حاسب متصل بالإنترنت ومزوّد بأدوات سطر الأوامر السحابية',
            'Well-Architected Framework whitepapers (cost and security pillars)' => 'أوراق إطار العمل المحكم معمارياً (محورا التكلفة والأمن)',
            // SWE 401
            'Develop the ability to plan, perform and justify software quality assurance activities across the development life cycle.' => 'تنمية القدرة على تخطيط أنشطة ضمان جودة البرمجيات وتنفيذها وتبريرها عبر دورة حياة التطوير.',
            'Lectures, inspection workshops, a team QA-plan project and reflective writing.' => 'محاضرات، وورش عمل للفحص، ومشروع جماعي لخطة ضمان الجودة، وكتابة تأملية.',
            'Describe software quality models and standards such as ISO/IEC 25010 and CMMI.' => 'وصف نماذج جودة البرمجيات ومعاييرها مثل ISO/IEC 25010 وCMMI.',
            'Apply review and inspection techniques to software artifacts.' => 'تطبيق أساليب المراجعة والفحص على مخرجات البرمجيات.',
            'Design a test and quality assurance plan for a software project.' => 'تصميم خطة اختبار وضمان جودة لمشروع برمجي.',
            'Justify quality decisions in a written report to project stakeholders.' => 'تبرير قرارات الجودة في تقرير مكتوب موجّه إلى أصحاب المصلحة في المشروع.',
            'Write a quality report.' => 'كتابة تقرير جودة.',
            'QA plan project' => 'مشروع خطة ضمان الجودة',
            'Software quality concepts and models' => 'مفاهيم جودة البرمجيات ونماذجها',
            'Standards: ISO/IEC 25010, ISO 9001, CMMI' => 'المعايير: ISO/IEC 25010 وISO 9001 وCMMI',
            'Reviews, walkthroughs and inspections' => 'المراجعات والجولات التفقدية والفحوص',
            'Test planning and test design' => 'تخطيط الاختبار وتصميمه',
            'Quality metrics and reporting' => 'مقاييس الجودة وإعداد التقارير',
            'ISO/IEC 25010 product quality model (summary notes)' => 'نموذج جودة المنتج ISO/IEC 25010 (ملخص)',
            'Software lab with test-management tools' => 'معمل برمجيات مزوّد بأدوات إدارة الاختبار',
            // SWE 302
            'Prepare students to design and evaluate software architectures that satisfy functional and quality requirements.' => 'إعداد الطلاب لتصميم معماريات برمجية تلبي المتطلبات الوظيفية ومتطلبات الجودة وتقييمها.',
            'Lectures, architecture katas, design studio sessions and peer design reviews.' => 'محاضرات، وتمارين معمارية قصيرة، وجلسات استوديو للتصميم، ومراجعات تصميم بين الأقران.',
            'Explain architectural styles and patterns such as layered, client-server and MVC.' => 'شرح الطرز والأنماط المعمارية مثل المعمارية الطبقية ونموذج العميل والخادم وMVC.',
            'Design a software architecture that satisfies functional and quality requirements.' => 'تصميم معمارية برمجية تلبي المتطلبات الوظيفية ومتطلبات الجودة.',
            'Evaluate alternative designs using quality-attribute trade-off analysis.' => 'تقييم التصاميم البديلة باستخدام تحليل الموازنة بين سمات الجودة.',
            'Communicate design decisions through architecture documentation and presentation.' => 'إيصال قرارات التصميم من خلال توثيق المعمارية وعرضها.',
            'Design project' => 'مشروع التصميم',
            'Architecture concepts and views' => 'مفاهيم المعمارية وطرق عرضها',
            'Architectural styles and patterns' => 'الطرز والأنماط المعمارية',
            'Quality attributes and tactics' => 'سمات الجودة وأساليب تحقيقها',
            'Design evaluation (ATAM-style trade-offs)' => 'تقييم التصميم (موازنات على طريقة ATAM)',
            'Documenting architecture' => 'توثيق المعمارية',
            'C4 model and UML modelling tool licences' => 'تراخيص أدوات النمذجة C4 وUML',
            'Design studio room with projection' => 'قاعة استوديو تصميم مزوّدة بجهاز عرض',
            // SWE 412
            'Enable students to design, build and evaluate usable mobile applications.' => 'تمكين الطلاب من تصميم تطبيقات أجهزة محمولة سهلة الاستخدام وبنائها وتقييمها.',
            'Hands-on labs, iterative app project, usability testing sessions.' => 'معامل تطبيقية، ومشروع تطبيق تكراري، وجلسات لاختبار قابلية الاستخدام.',
            'Describe mobile platform architectures and application life cycles.' => 'وصف معماريات منصات الأجهزة المحمولة ودورات حياة التطبيقات.',
            'Develop a mobile application that uses local storage and network services.' => 'تطوير تطبيق للأجهزة المحمولة يستخدم التخزين المحلي وخدمات الشبكة.',
            'Evaluate the usability of a mobile interface with representative users.' => 'تقييم قابلية استخدام واجهة تطبيق محمول مع مستخدمين ممثلين.',
            'Understand security risks in mobile applications.' => 'فهم المخاطر الأمنية في تطبيقات الأجهزة المحمولة.',
            'Analyze security risks in mobile applications and apply appropriate mitigations.' => 'تحليل المخاطر الأمنية في تطبيقات الأجهزة المحمولة وتطبيق الإجراءات المناسبة للحد منها.',
            'Lab assignments' => 'تكليفات المعمل',
            'Mobile app project' => 'مشروع تطبيق الأجهزة المحمولة',
            'Mobile platforms and app life cycle' => 'منصات الأجهزة المحمولة ودورة حياة التطبيق',
            'UI patterns and navigation' => 'أنماط واجهة المستخدم والتنقل',
            'Local storage and networking' => 'التخزين المحلي والشبكات',
            'Usability evaluation' => 'تقييم قابلية الاستخدام',
            'Testing and publishing' => 'الاختبار والنشر',
            'Platform developer documentation (Android / iOS)' => 'وثائق المطورين للمنصات (أندرويد / iOS)',
            'Mobile development lab with test devices' => 'معمل تطوير تطبيقات محمولة مزوّد بأجهزة اختبار',
            // CIS 491
            'Guide student teams to formulate and design a capstone software project.' => 'توجيه فرق الطلاب إلى صياغة مشروع تخرج برمجي وتصميمه.',
            'Supervised team work, milestone reviews, proposal defence.' => 'عمل جماعي بإشراف، ومراجعات للمراحل الرئيسة، ومناقشة المقترح.',
            'Formulate a software project proposal with measurable requirements.' => 'صياغة مقترح مشروع برمجي بمتطلبات قابلة للقياس.',
            'Design a solution architecture for the proposed system.' => 'تصميم معمارية الحل للنظام المقترح.',
            'Present the project plan to a technical audience.' => 'عرض خطة المشروع على جمهور تقني.',
            'Plan team responsibilities and professional conduct for the project.' => 'تخطيط مسؤوليات الفريق والسلوك المهني في المشروع.',
            'Proposal and design report' => 'تقرير المقترح والتصميم',
            'Progress presentation' => 'عرض التقدم',
            'Project selection and scoping' => 'اختيار المشروع وتحديد نطاقه',
            'Requirements and proposal writing' => 'المتطلبات وكتابة المقترح',
            'Solution design' => 'تصميم الحل',
            'Project planning and teamwork' => 'تخطيط المشروع والعمل الجماعي',
            'YU graduation project handbook' => 'دليل مشاريع التخرج في جامعة اليمامة',
            'Project lab and supervisor meeting rooms' => 'معمل المشاريع وقاعات الاجتماع بالمشرفين',
            // CNE 307
            'Develop the knowledge and practical skills to secure enterprise networks.' => 'تنمية المعرفة والمهارات العملية اللازمة لتأمين شبكات المؤسسات.',
            'Lectures, hands-on security labs and incident-analysis case studies.' => 'محاضرات، ومعامل أمن تطبيقية، ودراسات حالة لتحليل الحوادث.',
            'Explain network security threats, vulnerabilities and attack techniques.' => 'شرح تهديدات أمن الشبكات وثغراتها وأساليب الهجوم.',
            'Configure firewalls, VPNs and intrusion detection to secure a network.' => 'إعداد جدران الحماية والشبكات الافتراضية الخاصة وأنظمة كشف التسلل لتأمين شبكة.',
            'Analyze security incidents using packet captures and logs.' => 'تحليل الحوادث الأمنية باستخدام التقاط الحزم والسجلات.',
            'Recognize ethical and legal responsibilities in network security practice.' => 'إدراك المسؤوليات الأخلاقية والقانونية في ممارسة أمن الشبكات.',
            'Lab work' => 'الأعمال المعملية',
            'Threats and attack techniques' => 'التهديدات وأساليب الهجوم',
            'Firewalls and VPNs' => 'جدران الحماية والشبكات الافتراضية الخاصة',
            'Intrusion detection and monitoring' => 'كشف التسلل والمراقبة',
            'Incident analysis' => 'تحليل الحوادث',
            'Ethics and cyber law' => 'الأخلاقيات والقانون السيبراني',
            'Networking lab with virtualised security appliances' => 'معمل شبكات مزوّد بأجهزة أمنية افتراضية',
            // ACC 311
            'Build competence in recognising, measuring and reporting financial information under IFRS as endorsed in Saudi Arabia.' => 'بناء الكفاءة في إثبات المعلومات المالية وقياسها والإفصاح عنها وفق المعايير الدولية للتقرير المالي المعتمدة في المملكة العربية السعودية.',
            'Lectures, worked problems, case analysis.' => 'محاضرات، وحل مسائل تطبيقية، وتحليل حالات.',
            'Explain the conceptual framework and IFRS recognition and measurement principles.' => 'شرح الإطار المفاهيمي ومبادئ الإثبات والقياس في المعايير الدولية للتقرير المالي.',
            'Prepare financial statements in accordance with IFRS as endorsed in Saudi Arabia.' => 'إعداد القوائم المالية وفق المعايير الدولية للتقرير المالي المعتمدة في المملكة العربية السعودية.',
            'Analyze accounting transactions for revenue, receivables and inventory.' => 'تحليل المعاملات المحاسبية للإيرادات والذمم المدينة والمخزون.',
            'Demonstrate ethical judgement in accounting policy choices.' => 'إظهار الحكم الأخلاقي في اختيار السياسات المحاسبية.',
            'Case study' => 'دراسة حالة',
            'Conceptual framework' => 'الإطار المفاهيمي',
            'Revenue recognition (IFRS 15)' => 'إثبات الإيرادات (المعيار الدولي 15)',
            'Receivables and inventory' => 'الذمم المدينة والمخزون',
            'Financial statement preparation' => 'إعداد القوائم المالية',
            'SOCPA-endorsed IFRS standards' => 'المعايير الدولية للتقرير المالي المعتمدة من الهيئة السعودية للمراجعين والمحاسبين',
            // MIS 327
            'Enable students to design and query relational databases that support business processes.' => 'تمكين الطلاب من تصميم قواعد بيانات علائقية تدعم عمليات الأعمال والاستعلام منها.',
            'Lectures, SQL labs, team database project with a business client brief.' => 'محاضرات، ومعامل SQL، ومشروع قاعدة بيانات جماعي لعميل من قطاع الأعمال.',
            'Describe relational database concepts and the relational model.' => 'وصف مفاهيم قواعد البيانات العلائقية والنموذج العلائقي.',
            'Design a normalized database schema from business requirements.' => 'تصميم مخطط قاعدة بيانات مُطبَّع انطلاقاً من متطلبات الأعمال.',
            'Write SQL queries to retrieve and manipulate business data.' => 'كتابة استعلامات SQL لاسترجاع بيانات الأعمال ومعالجتها.',
            'Work in a team to deliver a database project for a business client.' => 'العمل ضمن فريق لتسليم مشروع قاعدة بيانات لعميل من قطاع الأعمال.',
            'SQL labs' => 'معامل SQL',
            'Database project' => 'مشروع قاعدة البيانات',
            'Relational model' => 'النموذج العلائقي',
            'ER modelling and normalisation' => 'نمذجة الكيانات والعلاقات والتطبيع',
            'SQL' => 'لغة SQL',
            'Database projects' => 'مشاريع قواعد البيانات',
            'Lab with a relational DBMS' => 'معمل مزوّد بنظام لإدارة قواعد البيانات العلائقية',
            // Decisions, comments, evidence and improvement actions in the story
            'CLO4 is too generic: state what the report justifies and for whom, so it can be assessed against SO3/SO4.' => 'المخرج 4 عام جداً: حدّد ما يبرره التقرير ولمن، حتى يمكن تقييمه مقابل SO3 وSO4.',
            'Revised CLO4 is assessable.' => 'المخرج 4 بعد التعديل قابل للتقييم.',
            'Capstone structure follows the graduation project handbook.' => 'بنية مقرر التخرج تتبع دليل مشاريع التخرج.',
            'Approved for this cycle. The 70% report weighting exceeds the single-assessment policy; submit a formal exception with justification before the next offering.' => 'اعتُمد لهذه الدورة. وزن التقرير البالغ 70% يتجاوز الحد المسموح لتقييم واحد؛ قدّم طلب استثناء رسمياً مع المبررات قبل الطرح القادم.',
            'Final exam paper and model answers' => 'ورقة الاختبار النهائي ونماذج الإجابة',
            'QA plan project rubric' => 'سلّم تقدير مشروع خطة ضمان الجودة',
            'Quiz 1 paper (both sections)' => 'ورقة الاختبار القصير 1 (الشعبتان)',
            'Midterm exam paper' => 'ورقة الاختبار النصفي',
            'CLO3 (test and QA planning) was the weakest outcome. Most teams produced test cases but could not derive a coverage-driven test plan from requirements; the project rubric showed the gap clearly while the final exam questions on planning were often skipped.' => 'كان المخرج 3 (تخطيط الاختبار وضمان الجودة) أضعف المخرجات. أعدّت معظم الفرق حالات اختبار لكنها لم تتمكن من اشتقاق خطة اختبار قائمة على التغطية من المتطلبات؛ وقد أظهر سلّم تقدير المشروع هذه الفجوة بوضوح، بينما تجاوز كثير من الطلاب أسئلة التخطيط في الاختبار النهائي.',
            'CLO3 improved after the test-design labs (more teams produced requirement-based test plans) but is still below target. Students now struggle mainly with risk-based prioritisation and estimating test effort.' => 'تحسّن المخرج 3 بعد معامل تصميم الاختبارات (إذ أعدّت فرق أكثر خطط اختبار قائمة على المتطلبات)، لكنه ما زال دون المستهدف. ويواجه الطلاب الآن صعوبة أساساً في ترتيب الأولويات حسب المخاطر وتقدير جهد الاختبار.',
            'Design-project architectures were often not traceable to quality requirements (CLO2). Teams documented components well but rarely justified decisions against performance or security scenarios.' => 'كثيراً ما تعذّر ربط معماريات مشروع التصميم بمتطلبات الجودة (المخرج 2). وثّقت الفرق المكونات جيداً لكنها نادراً ما بررت قراراتها في ضوء سيناريوهات الأداء أو الأمن.',
            'SQL proficiency (CLO3) dropped this term: many students had less prior exposure to querying, and the SQL labs were compressed into fewer weeks after the mid-semester break.' => 'انخفض إتقان SQL (المخرج 3) هذا الفصل: إذ كانت خبرة كثير من الطلاب السابقة في كتابة الاستعلامات أقل، وضُغطت معامل SQL في أسابيع أقل بعد إجازة منتصف الفصل.',
            'Introduce three weekly test-design labs (weeks 9–11) with rubric-based formative feedback, and add a graded test-plan checkpoint in week 10 before the final project submission.' => 'إضافة ثلاثة معامل أسبوعية لتصميم الاختبارات (الأسابيع 9–11) مع تغذية راجعة تكوينية قائمة على سلّم التقدير، وإضافة نقطة تحقق مقيَّمة لخطة الاختبار في الأسبوع 10 قبل تسليم المشروع النهائي.',
            'Add a risk-based test prioritisation case study and peer review of test plans; align the final-exam planning question with the project rubric so CLO3 is assessed consistently.' => 'إضافة دراسة حالة لترتيب أولويات الاختبار حسب المخاطر ومراجعة الأقران لخطط الاختبار؛ ومواءمة سؤال التخطيط في الاختبار النهائي مع سلّم تقدير المشروع ليُقيَّم المخرج 3 بصورة متسقة.',
            'Introduce quality-attribute scenario templates in the design studio and a mid-project architecture review against those scenarios.' => 'اعتماد قوالب سيناريوهات سمات الجودة في استوديو التصميم، وإجراء مراجعة للمعمارية في منتصف المشروع في ضوء تلك السيناريوهات.',
            'Spread SQL labs across eight weeks and add an auto-graded SQL practice set with weekly feedback.' => 'توزيع معامل SQL على ثمانية أسابيع وإضافة مجموعة تمارين SQL مصححة آلياً مع تغذية راجعة أسبوعية.',
            'Three test-design labs delivered (weeks 9–11) with rubric feedback; the week-10 test-plan checkpoint was graded for all 10 teams.' => 'نُفّذت ثلاثة معامل لتصميم الاختبارات (الأسابيع 9–11) مع تغذية راجعة وفق سلّم التقدير، وقُيّمت نقطة التحقق لخطة الاختبار في الأسبوع 10 لجميع الفرق العشرة.',
            "The proposal and design report is the capstone's integrating deliverable and is assessed through three staged milestones (proposal, requirements, design) by a panel of two examiners, as set out in the YU graduation project handbook. Splitting it would duplicate the milestone rubric." => 'تقرير المقترح والتصميم هو المُخرَج التكاملي لمقرر التخرج، ويُقيَّم عبر ثلاث مراحل متتالية (المقترح، المتطلبات، التصميم) من قِبل لجنة من مُقيِّمَين، كما ينص دليل مشاريع التخرج في جامعة اليمامة. وتجزئته ستكرر سلّم تقدير المراحل.',
            'Specifications approved by the College of Business council (2024-2025), migrated into SAQF' => 'توصيفات اعتمدها مجلس كلية إدارة الأعمال (2024-2025)، نُقلت إلى SAQF',
            'Quiz 1 and midterm grades' => 'درجات الاختبار القصير 1 والاختبار النصفي',
            'Quiz and midterm grades' => 'درجات الاختبار القصير والاختبار النصفي',
            'Quiz grades' => 'درجات الاختبار القصير',
            'Midterm exam grades' => 'درجات الاختبار النصفي',
            'Final gradebook export' => 'تصدير سجل الدرجات النهائي',
            'Quiz' => 'اختبار قصير',
            'Quiz 1' => 'الاختبار القصير 1',
            'Midterm exam' => 'الاختبار النصفي',
            'Final exam' => 'الاختبار النهائي',
            'Approved by HoD; all deterministic checks passed.' => 'اعتمده رئيس القسم؛ واجتاز كل الفحوص الآلية.',
            'Revised CLO4 is assessable.' => 'أصبح CLO4 بعد تعديله قابلاً للتقييم.',
            'Approved for this cycle. The 70% report weighting exceeds the single-assessment policy; submit a formal exception with justification before the next offering.' => 'اعتُمد لهذه الدورة. وزن التقرير البالغ 70% يتجاوز سياسة التقييم الواحد؛ قدّم طلب استثناء رسمياً مع المبررات قبل الطرح القادم.',
            'Only non-academic sections changed (content, resources, wording); approved automatically by policy.' => 'تغيّرت أقسام غير أكاديمية فقط (المحتوى والمصادر والصياغة)؛ واعتُمد تلقائياً وفق السياسة.',
            'SIS assigns SWE 413 Design Patterns to Dr. Faisal Al-Dosari, a newly hired instructor SAQF does not know yet' => 'نظام معلومات الطلاب يُسند مقرر SWE 413 أنماط التصميم إلى د. فيصل الدوسري، وهو عضو هيئة تدريس جديد لا يعرفه SAQF بعد',
        ],
    ];
}
