<?php
declare(strict_types=1);

namespace Saqf\Demo;

/**
 * The demonstration scenario. All people are FICTIONAL demo accounts; programs,
 * courses, prerequisites and PLOs come from the YU public study-plan snapshot.
 * Student results are synthetic and pseudonymous, generated by bin/build_demo_data.php.
 *
 * The story travels through every role:
 *  - Software Engineering (Computer Engineering Dept., College of Engineering)
 *  - SWE 401 misses CLO3 two terms running; the first improvement action is followed
 *    by a measurable improvement, but the gap recurs → HoD sees a recurring gap.
 *  - SWE SO2 stays below target across terms → the Dean sees a persistent PLO issue.
 *  - SWE 412 is re-assigned to a new instructor who starts a revision with four
 *    deterministic errors (the live demo fixes them).
 *  - CIS 491 carries a capstone weighting above policy → a justified exception request for QA.
 *  - SWE 302 midterm grades are "about to be published" by the LMS → early warning on delivery.
 *  - Business: ACC 311 (healthy, shared with Finance), MIS 327 (one gap with an action).
 *  - Data: the published MIS plan lists MIS 316 with two different credit values.
 */
final class Story
{
    public const PASSWORD = 'Yamamah@2026';
    /** The demo scenario's "today": Fall 2026, week 6. The installer anchors the demo clock here. */
    public const DEMO_NOW = '2026-10-01 09:00:00';

    public const USERS = [
        // username, full name, title, role, department code, college code, external id, email
        ['f.sara', 'Dr. Sara Al-Qahtani', 'Associate Professor', 'faculty', 'CED', null, 'YU-F1021'],
        ['f.omar', 'Dr. Omar Al-Harbi', 'Assistant Professor', 'faculty', 'CED', null, 'YU-F1034'],
        ['f.faisal', 'Dr. Faisal Al-Dosari', 'Assistant Professor', 'faculty', 'CED', null, 'YU-F1047'],
        ['f.yousef', 'Dr. Yousef Al-Malki', 'Professor', 'faculty', 'CED', null, 'YU-F1009'],
        ['f.lina', 'Dr. Lina Al-Mutairi', 'Assistant Professor', 'faculty', 'CED', null, 'YU-F1052'],
        ['f.noura', 'Dr. Noura Al-Shehri', 'Assistant Professor', 'faculty', 'AFD', null, 'YU-F2011'],
        ['f.khalid', 'Dr. Khalid Al-Ghamdi', 'Associate Professor', 'faculty', 'MISD', null, 'YU-F2024'],
        ['hod.ced', 'Dr. Abdullah Al-Otaibi', 'Head, Computer Engineering Department', 'hod', 'CED', null, 'YU-H0101'],
        ['hod.afd', 'Dr. Reem Al-Zahrani', 'Head, Accounting & Finance Department', 'hod', 'AFD', null, 'YU-H0201'],
        ['hod.misd', 'Dr. Nasser Al-Qurashi', 'Head, MIS Department', 'hod', 'MISD', null, 'YU-H0202'],
        ['qa.director', 'Dr. Huda Al-Rashid', 'Director, Quality & Academic Accreditation', 'qa', null, null, 'YU-Q0001'],
        ['dean.coe', 'Dr. Mansour Al-Shammari', 'Dean, College of Engineering', 'dean', null, 'COE', 'YU-D0001'],
        ['dean.cob', 'Dr. Amal Al-Juhani', 'Dean, College of Business', 'dean', null, 'COB', 'YU-D0002'],
        ['vp.academic', 'Dr. Fahad Al-Sudairi', 'Vice President for Academic Affairs', 'leadership', null, null, 'YU-L0001'],
        ['it.admin', 'Saleh Al-Anazi', 'IT Systems Administrator', 'admin', null, null, 'YU-IT001'],
    ];

    public const TERMS = [
        ['code' => '2025-1', 'name' => 'Fall 2025', 'academic_year' => '2025-2026', 'sequence' => 1, 'starts_on' => '2025-08-24', 'ends_on' => '2025-12-18', 'grades_due_on' => '2025-12-28'],
        ['code' => '2025-2', 'name' => 'Spring 2026', 'academic_year' => '2025-2026', 'sequence' => 2, 'starts_on' => '2026-01-11', 'ends_on' => '2026-05-14', 'grades_due_on' => '2026-05-24'],
        ['code' => '2026-1', 'name' => 'Fall 2026', 'academic_year' => '2026-2027', 'sequence' => 3, 'starts_on' => '2026-08-23', 'ends_on' => '2026-12-17', 'grades_due_on' => '2026-12-27'],
        ['code' => '2026-2', 'name' => 'Spring 2027', 'academic_year' => '2026-2027', 'sequence' => 4, 'starts_on' => '2027-01-10', 'ends_on' => '2027-05-13', 'grades_due_on' => '2027-05-23'],
    ];

    /**
     * Specifications. clos: [statement, domain, [program => [PLO codes]]].
     * assessments: [name, kind, weight, week, [CLO indexes (1-based)]].
     */
    public const SPECS = [
        'CIS 443' => [
            'author' => 'f.sara',
            'objectives' => 'Enable students to design, deploy and evaluate secure, cost-aware applications on public cloud platforms.',
            'strategies' => 'Interactive lectures, guided cloud labs, a team deployment project and case-based discussions.',
            'clos' => [
                ['Explain cloud service and deployment models and their trade-offs.', 'Knowledge and Understanding', ['SWE' => ['SO1']]],
                ['Design and deploy a scalable application on a cloud platform.', 'Skills', ['SWE' => ['SO2']]],
                ['Evaluate the security and cost implications of a cloud architecture.', 'Skills', ['SWE' => ['SO1', 'SO4']]],
                ['Collaborate in a team to present a cloud migration proposal.', 'Values, Autonomy, and Responsibility', ['SWE' => ['SO3', 'SO5']]],
            ],
            'assessments' => [
                ['Quiz 1', 'quiz', 10, 4, [1]],
                ['Midterm exam', 'midterm', 25, 7, [1, 3]],
                ['Cloud deployment project', 'project', 30, 13, [2, 4]],
                ['Team presentation', 'presentation', 10, 14, [4]],
                ['Final exam', 'final', 25, 16, [1, 2, 3]],
            ],
            'topics' => [['Cloud computing concepts and service models', 6], ['Virtualisation and containers', 9], ['Cloud storage and networking', 9], ['Deploying and scaling applications', 12], ['Cloud security, cost and governance', 9]],
            'resources' => [['essential', 'Erl, T. et al. Cloud Computing: Concepts, Technology & Architecture (2nd ed.)'], ['electronic', 'Cloud provider academic labs (sandbox accounts)'], ['facility', 'Computer lab with internet access and cloud CLI tools']],
        ],
        'SWE 401' => [
            'author' => 'f.omar',
            'objectives' => 'Develop the ability to plan, perform and justify software quality assurance activities across the development life cycle.',
            'strategies' => 'Lectures, inspection workshops, a team QA-plan project and reflective writing.',
            'clos' => [
                ['Describe software quality models and standards such as ISO/IEC 25010 and CMMI.', 'Knowledge and Understanding', ['SWE' => ['SO1']]],
                ['Apply review and inspection techniques to software artifacts.', 'Skills', ['SWE' => ['SO1', 'SO2']]],
                ['Design a test and quality assurance plan for a software project.', 'Skills', ['SWE' => ['SO2']]],
                ['Justify quality decisions in a written report to project stakeholders.', 'Values, Autonomy, and Responsibility', ['SWE' => ['SO3', 'SO4']]],
            ],
            'assessments' => [
                ['Quiz', 'quiz', 10, 4, [1]],
                ['Midterm exam', 'midterm', 30, 8, [1, 2]],
                ['QA plan project', 'project', 30, 13, [3, 4]],
                ['Final exam', 'final', 30, 16, [2, 3]],
            ],
            'topics' => [['Software quality concepts and models', 6], ['Standards: ISO/IEC 25010, ISO 9001, CMMI', 6], ['Reviews, walkthroughs and inspections', 9], ['Test planning and test design', 12], ['Quality metrics and reporting', 9]],
            'resources' => [['essential', 'Galin, D. Software Quality: Concepts and Practice'], ['supportive', 'ISO/IEC 25010 product quality model (summary notes)'], ['facility', 'Software lab with test-management tools']],
        ],
        'SWE 302' => [
            'author' => 'f.sara',
            'objectives' => 'Prepare students to design and evaluate software architectures that satisfy functional and quality requirements.',
            'strategies' => 'Lectures, architecture katas, design studio sessions and peer design reviews.',
            'clos' => [
                ['Explain architectural styles and patterns such as layered, client-server and MVC.', 'Knowledge and Understanding', ['SWE' => ['SO1']]],
                ['Design a software architecture that satisfies functional and quality requirements.', 'Skills', ['SWE' => ['SO2']]],
                ['Evaluate alternative designs using quality-attribute trade-off analysis.', 'Skills', ['SWE' => ['SO1', 'SO2']]],
                ['Communicate design decisions through architecture documentation and presentation.', 'Values, Autonomy, and Responsibility', ['SWE' => ['SO3', 'SO5']]],
            ],
            'assessments' => [
                ['Quiz', 'quiz', 10, 3, [1]],
                ['Midterm exam', 'midterm', 25, 7, [1, 3]],
                ['Design project', 'project', 35, 12, [2, 4]],
                ['Final exam', 'final', 30, 16, [2, 3]],
            ],
            'topics' => [['Architecture concepts and views', 6], ['Architectural styles and patterns', 12], ['Quality attributes and tactics', 9], ['Design evaluation (ATAM-style trade-offs)', 9], ['Documenting architecture', 6]],
            'resources' => [['essential', 'Bass, Clements & Kazman. Software Architecture in Practice (4th ed.)'], ['electronic', 'C4 model and UML modelling tool licences'], ['facility', 'Design studio room with projection']],
        ],
        'SWE 412' => [
            'author' => 'f.omar',
            'objectives' => 'Enable students to design, build and evaluate usable mobile applications.',
            'strategies' => 'Hands-on labs, iterative app project, usability testing sessions.',
            'clos' => [
                ['Describe mobile platform architectures and application life cycles.', 'Knowledge and Understanding', ['SWE' => ['SO1']]],
                ['Develop a mobile application that uses local storage and network services.', 'Skills', ['SWE' => ['SO2']]],
                ['Evaluate the usability of a mobile interface with representative users.', 'Skills', ['SWE' => ['SO2', 'SO3']]],
            ],
            'assessments' => [
                ['Lab assignments', 'lab', 20, 10, [2]],
                ['Midterm exam', 'midterm', 25, 7, [1]],
                ['Mobile app project', 'project', 35, 14, [2, 3]],
                ['Final exam', 'final', 20, 16, [1, 3]],
            ],
            'topics' => [['Mobile platforms and app life cycle', 6], ['UI patterns and navigation', 9], ['Local storage and networking', 12], ['Usability evaluation', 6], ['Testing and publishing', 6]],
            'resources' => [['essential', 'Platform developer documentation (Android / iOS)'], ['facility', 'Mobile development lab with test devices']],
        ],
        'CIS 491' => [
            'author' => 'f.yousef',
            'objectives' => 'Guide student teams to formulate and design a capstone software project.',
            'strategies' => 'Supervised team work, milestone reviews, proposal defence.',
            'clos' => [
                ['Formulate a software project proposal with measurable requirements.', 'Skills', ['SWE' => ['SO1'], 'CNE' => ['SO1']]],
                ['Design a solution architecture for the proposed system.', 'Skills', ['SWE' => ['SO2'], 'CNE' => ['SO2']]],
                ['Present the project plan to a technical audience.', 'Values, Autonomy, and Responsibility', ['SWE' => ['SO3'], 'CNE' => ['SO3']]],
                ['Plan team responsibilities and professional conduct for the project.', 'Values, Autonomy, and Responsibility', ['SWE' => ['SO4', 'SO5'], 'CNE' => ['SO4', 'SO5']]],
            ],
            'assessments' => [
                ['Proposal and design report', 'report', 70, 14, [1, 2, 4]],
                ['Progress presentation', 'presentation', 30, 15, [3, 4]],
            ],
            'topics' => [['Project selection and scoping', 6], ['Requirements and proposal writing', 12], ['Solution design', 15], ['Project planning and teamwork', 9]],
            'resources' => [['essential', 'YU graduation project handbook'], ['facility', 'Project lab and supervisor meeting rooms']],
        ],
        'CNE 307' => [
            'author' => 'f.lina',
            'objectives' => 'Develop the knowledge and practical skills to secure enterprise networks.',
            'strategies' => 'Lectures, hands-on security labs and incident-analysis case studies.',
            'clos' => [
                ['Explain network security threats, vulnerabilities and attack techniques.', 'Knowledge and Understanding', ['CNE' => ['SO1']]],
                ['Configure firewalls, VPNs and intrusion detection to secure a network.', 'Skills', ['CNE' => ['SO2', 'SO6']]],
                ['Analyze security incidents using packet captures and logs.', 'Skills', ['CNE' => ['SO6']]],
                ['Recognize ethical and legal responsibilities in network security practice.', 'Values, Autonomy, and Responsibility', ['CNE' => ['SO4']]],
            ],
            'assessments' => [
                ['Quiz', 'quiz', 10, 4, [1]],
                ['Lab work', 'lab', 25, 12, [2, 3]],
                ['Midterm exam', 'midterm', 25, 8, [1, 4]],
                ['Final exam', 'final', 40, 16, [2, 3, 4]],
            ],
            'topics' => [['Threats and attack techniques', 9], ['Firewalls and VPNs', 12], ['Intrusion detection and monitoring', 12], ['Incident analysis', 6], ['Ethics and cyber law', 3]],
            'resources' => [['essential', 'Stallings, W. Network Security Essentials'], ['facility', 'Networking lab with virtualised security appliances']],
        ],
        'ACC 311' => [
            'author' => 'f.noura',
            'objectives' => 'Build competence in recognising, measuring and reporting financial information under IFRS as endorsed in Saudi Arabia.',
            'strategies' => 'Lectures, worked problems, case analysis.',
            'clos' => [
                ['Explain the conceptual framework and IFRS recognition and measurement principles.', 'Knowledge and Understanding', ['ACC' => ['PLO1', 'PLO2'], 'FIN' => ['PLO1']]],
                ['Prepare financial statements in accordance with IFRS as endorsed in Saudi Arabia.', 'Skills', ['ACC' => ['PLO3'], 'FIN' => ['PLO3']]],
                ['Analyze accounting transactions for revenue, receivables and inventory.', 'Skills', ['ACC' => ['PLO4', 'PLO5'], 'FIN' => ['PLO5']]],
                ['Demonstrate ethical judgement in accounting policy choices.', 'Values, Autonomy, and Responsibility', ['ACC' => ['PLO8'], 'FIN' => ['PLO8']]],
            ],
            'assessments' => [
                ['Quiz', 'quiz', 10, 4, [1]],
                ['Midterm exam', 'midterm', 30, 8, [1, 3]],
                ['Case study', 'assignment', 20, 12, [3, 4]],
                ['Final exam', 'final', 40, 16, [2, 3]],
            ],
            'topics' => [['Conceptual framework', 6], ['Revenue recognition (IFRS 15)', 9], ['Receivables and inventory', 12], ['Financial statement preparation', 12]],
            'resources' => [['essential', 'Kieso, Weygandt & Warfield. Intermediate Accounting (IFRS edition)'], ['electronic', 'SOCPA-endorsed IFRS standards']],
        ],
        'MIS 327' => [
            'author' => 'f.khalid',
            'objectives' => 'Enable students to design and query relational databases that support business processes.',
            'strategies' => 'Lectures, SQL labs, team database project with a business client brief.',
            'clos' => [
                ['Describe relational database concepts and the relational model.', 'Knowledge and Understanding', ['MIS' => ['SO1']]],
                ['Design a normalized database schema from business requirements.', 'Skills', ['MIS' => ['SO2']]],
                ['Write SQL queries to retrieve and manipulate business data.', 'Skills', ['MIS' => ['SO2', 'SO6']]],
                ['Work in a team to deliver a database project for a business client.', 'Values, Autonomy, and Responsibility', ['MIS' => ['SO5']]],
            ],
            'assessments' => [
                ['Quiz', 'quiz', 10, 4, [1]],
                ['SQL labs', 'lab', 20, 10, [3]],
                ['Midterm exam', 'midterm', 25, 8, [1, 2]],
                ['Database project', 'project', 25, 14, [2, 4]],
                ['Final exam', 'final', 20, 16, [3]],
            ],
            'topics' => [['Relational model', 6], ['ER modelling and normalisation', 12], ['SQL', 15], ['Database projects', 9]],
            'resources' => [['essential', 'Coronel & Morris. Database Systems: Design, Implementation, & Management'], ['facility', 'Lab with a relational DBMS']],
        ],
    ];

    /**
     * Offerings per term: course => [instructor, enrolled, [target CLO achievement % in CLO order], batches]
     * batches: [label, published_at, [assessment names]]; future dates = not yet published by the LMS.
     */
    public const OFFERINGS = [
        '2025-1' => [
            'CIS 443' => ['f.sara', 30, [80, 70, 73.3, 86.7]],
            'SWE 401' => ['f.omar', 30, [76.7, 70, 53.3, 80]],
            'SWE 302' => ['f.sara', 28, [78.6, 71.4, 71.4, 85.7]],
            'CIS 491' => ['f.yousef', 24, [70.8, 70.8, 83.3, 79.2]],
            'CNE 307' => ['f.lina', 26, [76.9, 73.1, 73.1, 84.6]],
            'ACC 311' => ['f.noura', 32, [78.1, 75, 71.9, 87.5]],
            'MIS 327' => ['f.khalid', 25, [80, 72, 72, 84]],
        ],
        '2025-2' => [
            'CIS 443' => ['f.sara', 32, [81.3, 71.9, 75, 87.5]],
            'SWE 401' => ['f.omar', 30, [80, 70, 63.3, 83.3]],
            'SWE 302' => ['f.sara', 30, [76.7, 63.3, 70, 83.3]],
            'SWE 412' => ['f.omar', 25, [84, 72, 72]],
            'CNE 307' => ['f.lina', 27, [77.8, 74.1, 74.1, 85.2]],
            'ACC 311' => ['f.noura', 30, [80, 76.7, 73.3, 86.7]],
            'MIS 327' => ['f.khalid', 26, [80.8, 73.1, 61.5, 84.6]],
        ],
        '2026-1' => [
            'CIS 443' => ['f.sara', 31, [77.4, null, 74.2, null], [['Quiz 1 and midterm grades', '2026-09-28 10:00:00', ['Quiz 1', 'Midterm exam']]]],
            'SWE 401' => ['f.omar', 29, [72.4, 72.4, null, null], [['Quiz and midterm grades', '2026-09-29 11:00:00', ['Quiz', 'Midterm exam']]]],
            'SWE 302' => ['f.sara', 30, [76.7, null, 60, null], [['Quiz grades', '2026-09-15 09:00:00', ['Quiz']], ['Midterm exam grades', '2026-10-20 09:00:00', ['Midterm exam']]]],
            'SWE 412' => ['f.faisal', 27, [null, null, null]],
            'CIS 491' => ['f.yousef', 22, [null, null, null, null]],
            'SWE 411' => ['f.yousef', 28, []],
            'CNE 307' => ['f.lina', 25, [76, null, null, null], [['Quiz grades', '2026-09-22 09:00:00', ['Quiz']]]],
            'ACC 311' => ['f.noura', 33, [78.8, null, 72.7, null], [['Quiz and midterm grades', '2026-09-30 12:00:00', ['Quiz', 'Midterm exam']]]],
            'MIS 327' => ['f.khalid', 24, [79.2, null, null, null], [['Quiz grades', '2026-09-21 09:00:00', ['Quiz']]]],
        ],
        '2026-2' => [
            'CIS 443' => ['f.sara', 30, []],
            'SWE 401' => ['f.omar', 30, []],
            'SWE 302' => ['f.faisal', 28, []],
            'SWE 412' => ['f.faisal', 26, []],
            'CIS 492' => ['f.yousef', 22, []],
            'CNE 307' => ['f.lina', 26, []],
            'ACC 311' => ['f.noura', 31, []],
            'MIS 327' => ['f.khalid', 25, []],
        ],
    ];

    /** Assignments the SIS "publishes later" — released from the admin integration simulator. */
    public const PENDING_ASSIGNMENTS = [
        ['term' => '2026-1', 'course' => 'SWE 413', 'instructor' => 'YU-F1047', 'sections' => 1, 'enrolled' => 18, 'label' => 'SIS assigns SWE 413 Design Patterns (elective) to Dr. Faisal Al-Dosari'],
    ];
}
