<?php

return [
    ['code' => 'CIS 103', 'title' => 'Programming Fundamentals I', 'credits' => 4, 'level' => 1, 'type' => ''],
    ['code' => 'CIS 104', 'title' => 'Programming Fundamentals II', 'credits' => 4, 'level' => 1, 'type' => ''],
    ['code' => 'CHM 101', 'title' => 'General Chemistry', 'credits' => 4, 'level' => 1, 'type' => ''],
    ['code' => 'PHY 103', 'title' => 'Physics I', 'credits' => 4, 'level' => 1, 'type' => ''],
    ['code' => 'MTH 106', 'title' => 'Discrete Mathematics', 'credits' => 3, 'level' => 1, 'type' => ''],
    ['code' => 'MTH 104', 'title' => 'Calculus I', 'credits' => 3, 'level' => 1, 'type' => ''],
    ['code' => 'ENG 101', 'title' => 'English Essay Writing', 'credits' => 3, 'level' => 1, 'type' => ''],
    ['code' => 'STT 103', 'title' => 'Probability and Statistics', 'credits' => 3, 'level' => 1, 'type' => ''],
    ['code' => 'ISL 101', 'title' => 'Foundation of Islamic Culture', 'credits' => 2, 'level' => 1, 'type' => ''],
    ['code' => 'ARB 102', 'title' => 'Communication Skills in Arabic', 'credits' => 2, 'level' => 1, 'type' => ''],
    ['code' => 'HSS 1', 'title' => 'Humanities / Social Science Elective I', 'credits' => 3, 'level' => 1, 'type' => 'Humanities / Social Science Elective'],
    ['code' => 'HSS 2', 'title' => 'Humanities / Social Science Elective II', 'credits' => 3, 'level' => 1, 'type' => 'Humanities / Social Science Elective'],

    ['code' => 'CIS 201', 'title' => 'Fundamentals of Web Design', 'credits' => 3, 'level' => 2, 'type' => ''],
    ['code' => 'CIS 221', 'title' => 'Introduction to Database Systems', 'credits' => 3, 'level' => 2, 'type' => ''],
    ['code' => 'CIS 202', 'title' => 'Data Structures', 'credits' => 3, 'level' => 2, 'type' => ''],
    ['code' => 'SWE 202', 'title' => 'Introduction to Software Engineering', 'credits' => 3, 'level' => 2, 'type' => ''],
    ['code' => 'MIS 201', 'title' => 'Introduction to Information Systems', 'credits' => 3, 'level' => 2, 'type' => ''],
    ['code' => 'NES 212', 'title' => 'Data Communications & Computer Networks', 'credits' => 3, 'level' => 2, 'type' => ''],
    ['code' => 'PHY 203', 'title' => 'Physics II', 'credits' => 4, 'level' => 2, 'type' => ''],
    ['code' => 'MTH 304', 'title' => 'Differential Equations', 'credits' => 3, 'level' => 2, 'type' => ''],
    ['code' => 'MTH 204', 'title' => 'Calculus II', 'credits' => 3, 'level' => 2, 'type' => ''],
    ['code' => 'ENG 201', 'title' => 'Technical Report Writing', 'credits' => 3, 'level' => 2, 'type' => ''],
    ['code' => 'ISL 202', 'title' => 'Financial Awareness', 'credits' => 2, 'level' => 2, 'type' => ''],
    ['code' => 'ARB 202', 'title' => 'Writing Skills in Arabic', 'credits' => 2, 'level' => 2, 'type' => ''],

    ['code' => 'CIS 304', 'title' => 'Computer Architecture', 'credits' => 3, 'level' => 3, 'type' => ''],
    ['code' => 'CIS 321', 'title' => 'Operating Systems', 'credits' => 3, 'level' => 3, 'type' => ''],
    ['code' => 'CIS 386', 'title' => 'Project Management', 'credits' => 3, 'level' => 3, 'type' => ''],
    ['code' => 'CIS 381', 'title' => 'Computer Ethics', 'credits' => 2, 'level' => 3, 'type' => ''],
    ['code' => 'CIS 383', 'title' => 'Cyber Security and Cryptography', 'credits' => 3, 'level' => 3, 'type' => ''],
    ['code' => 'CIS 316', 'title' => 'Introduction to Artificial Intelligence', 'credits' => 3, 'level' => 3, 'type' => ''],
    ['code' => 'SWE 300', 'title' => 'Software Process & Modelling', 'credits' => 3, 'level' => 3, 'type' => ''],
    ['code' => 'SWE 302', 'title' => 'Software Architecture & Design', 'credits' => 3, 'level' => 3, 'type' => ''],
    ['code' => 'SWE 301', 'title' => 'Software Requirements Engineering', 'credits' => 3, 'level' => 3, 'type' => ''],
    ['code' => 'SWE 312', 'title' => 'Software Construction & User Interface', 'credits' => 3, 'level' => 3, 'type' => ''],
    ['code' => 'MTH 301', 'title' => 'Linear Algebra', 'credits' => 3, 'level' => 3, 'type' => ''],
    ['code' => 'SWE 322', 'title' => 'Advanced Web Programming', 'credits' => 3, 'level' => 3, 'type' => ''],

    ['code' => 'CIS 491', 'title' => 'Graduation Project I', 'credits' => 3, 'level' => 4, 'type' => ''],
    ['code' => 'CIS 492', 'title' => 'Graduation Project II', 'credits' => 3, 'level' => 4, 'type' => ''],
    ['code' => 'CIS 443', 'title' => 'Cloud Computing', 'credits' => 3, 'level' => 4, 'type' => ''],
    ['code' => 'SWE 401', 'title' => 'Software Quality Assurance', 'credits' => 3, 'level' => 4, 'type' => ''],
    ['code' => 'SWE 321', 'title' => 'Advanced User Interface Design', 'credits' => 3, 'level' => 4, 'type' => ''],
    ['code' => 'SWE 411', 'title' => 'Software Verification & Validation', 'credits' => 3, 'level' => 4, 'type' => ''],
    ['code' => 'CSK 001', 'title' => 'Career Skills', 'credits' => 0, 'level' => 4, 'type' => ''],
    ['code' => 'CIS 490', 'title' => 'Cooperative Assignment', 'credits' => 6, 'level' => 4, 'type' => ''],

    ['code' => 'SWE 402', 'title' => 'Software Maintenance and Evolution', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],
    ['code' => 'SWE 413', 'title' => 'Design Patterns', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],
    ['code' => 'SWE 414', 'title' => 'Formal Methods in Software Engineering', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],
    ['code' => 'SWE 415', 'title' => 'Software Usability Engineering', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],
    ['code' => 'CIS 222', 'title' => 'Interactive Media', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],
    ['code' => 'SWE 412', 'title' => 'Mobile Application Development', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],
    ['code' => 'CIS 416', 'title' => 'Introduction to Machine Learning', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],
    ['code' => 'NES 424', 'title' => 'IOT architectures, protocols and security', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],
    ['code' => 'NES 481', 'title' => 'Security Policies and Procedures', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],
    ['code' => 'SWE 421', 'title' => 'Game Development', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],
    ['code' => 'SWE 429', 'title' => 'Selected Topics in Software Engineering', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],
    ['code' => 'MIS 432', 'title' => 'Enterprise Systems', 'credits' => 3, 'level' => 4, 'type' => 'SWE Elective'],

    ['code' => 'SOS 102', 'title' => 'Introduction to Social Science', 'credits' => 3, 'level' => 1, 'type' => 'Humanities / Social Science Elective'],
    ['code' => 'PHL 101', 'title' => 'Critical Thinking', 'credits' => 3, 'level' => 1, 'type' => 'Humanities / Social Science Elective'],
    ['code' => 'PSY 101', 'title' => 'Principle of Psychology', 'credits' => 3, 'level' => 1, 'type' => 'Humanities / Social Science Elective'],
    ['code' => 'SOS 101', 'title' => 'Saudi Heritage', 'credits' => 3, 'level' => 1, 'type' => 'Humanities / Social Science Elective'],
    ['code' => 'FRE 106', 'title' => 'Conversational French 1', 'credits' => 3, 'level' => 1, 'type' => 'Humanities / Social Science Elective'],
    ['code' => 'CHI 107', 'title' => 'Chinese Language', 'credits' => 3, 'level' => 1, 'type' => 'Humanities / Social Science Elective'],
    ['code' => 'ENG 103', 'title' => 'Introduction to English Literature', 'credits' => 3, 'level' => 1, 'type' => 'Humanities / Social Science Elective'],
];
